// sample_data/courses.ts
import { Course } from "../types/index";

export const courses: Course[] = [
  {
    id: "1",
    title: "Full Stack Web Development with MERN",
    description:
      "Master modern web development with MongoDB, Express.js, React, and Node.js. Build production-ready applications from scratch.",
    instructor: "Rajesh Kumar",
    instructorImage:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    price: 12999,
    originalPrice: 18999,
    duration: "16 weeks",
    level: "Intermediate",
    category: "Web Development",
    rating: 4.8,
    studentsEnrolled: 2456,
    image:
      "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=400&h=250&fit=crop",
    features: [
      "Live Interactive Sessions",
      "Real-world Projects",
      "Industry Mentorship",
      "Job Placement Assistance",
      "24/7 Community Support",
    ],
    curriculum: [
      "HTML5 & CSS3 Fundamentals",
      "JavaScript ES6+",
      "React.js & Redux",
      "Node.js & Express.js",
      "MongoDB & Database Design",
      "RESTful API Development",
      "Authentication & Security",
      "Deployment & DevOps",
    ],
    prerequisites: ["Basic programming knowledge", "Computer with internet"],
    certificateProvided: true,
    language: "English",
    lastUpdated: "2024-12-01",
    tags: ["React", "Node.js", "MongoDB", "JavaScript", "Full Stack"],
  },
  {
    id: "2",
    title: "Data Science & Machine Learning",
    description:
      "Comprehensive course covering Python, statistics, machine learning algorithms, and real-world data science projects.",
    instructor: "Dr. Priya Sharma",
    instructorImage:
      "https://images.unsplash.com/photo-1494790108755-2616b612b5bc?w=100&h=100&fit=crop&crop=face",
    price: 15999,
    originalPrice: 22999,
    duration: "20 weeks",
    level: "Beginner",
    category: "Data Science",
    rating: 4.9,
    studentsEnrolled: 1834,
    image:
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop",
    features: [
      "Python Programming",
      "Hands-on Projects",
      "Industry Case Studies",
      "Career Guidance",
      "Certification",
    ],
    curriculum: [
      "Python Fundamentals",
      "NumPy & Pandas",
      "Data Visualization",
      "Statistics & Probability",
      "Machine Learning Algorithms",
      "Deep Learning Basics",
      "Model Deployment",
      "Capstone Project",
    ],
    prerequisites: [
      "Basic mathematics",
      "No prior programming experience needed",
    ],
    certificateProvided: true,
    language: "English",
    lastUpdated: "2024-11-28",
    tags: ["Python", "Machine Learning", "Data Science", "AI", "Analytics"],
  },
  {
    id: "3",
    title: "Mobile App Development with React Native",
    description:
      "Build cross-platform mobile applications for iOS and Android using React Native and JavaScript.",
    instructor: "Arjun Patel",
    instructorImage:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    price: 10999,
    originalPrice: 16999,
    duration: "12 weeks",
    level: "Intermediate",
    category: "Mobile Development",
    rating: 4.7,
    studentsEnrolled: 1567,
    image:
      "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=250&fit=crop",
    features: [
      "Cross-platform Development",
      "Real Device Testing",
      "App Store Deployment",
      "Performance Optimization",
      "Push Notifications",
    ],
    curriculum: [
      "React Native Fundamentals",
      "Navigation & Routing",
      "State Management",
      "Native Modules",
      "API Integration",
      "Testing & Debugging",
      "App Store Submission",
      "Performance Optimization",
    ],
    prerequisites: ["JavaScript knowledge", "Basic React understanding"],
    certificateProvided: true,
    language: "English",
    lastUpdated: "2024-11-25",
    tags: ["React Native", "Mobile", "iOS", "Android", "JavaScript"],
  },
  {
    id: "4",
    title: "UI/UX Design Masterclass",
    description:
      "Learn user interface and user experience design principles with hands-on projects using Figma and Adobe XD.",
    instructor: "Sneha Reddy",
    instructorImage:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    price: 8999,
    originalPrice: 13999,
    duration: "10 weeks",
    level: "Beginner",
    category: "Design",
    rating: 4.6,
    studentsEnrolled: 2103,
    image:
      "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=250&fit=crop",
    features: [
      "Design Thinking Process",
      "Prototyping Tools",
      "User Research Methods",
      "Portfolio Development",
      "Industry Projects",
    ],
    curriculum: [
      "Design Fundamentals",
      "User Research",
      "Wireframing",
      "Prototyping",
      "Visual Design",
      "Usability Testing",
      "Design Systems",
      "Portfolio Creation",
    ],
    prerequisites: ["Creative mindset", "No prior design experience needed"],
    certificateProvided: true,
    language: "English",
    lastUpdated: "2024-11-30",
    tags: ["UI Design", "UX Design", "Figma", "Adobe XD", "Prototyping"],
  },
  {
    id: "5",
    title: "Cloud Computing with AWS",
    description:
      "Master Amazon Web Services and cloud computing concepts with hands-on labs and real-world scenarios.",
    instructor: "Vikram Singh",
    instructorImage:
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&h=100&fit=crop&crop=face",
    price: 13999,
    originalPrice: 19999,
    duration: "14 weeks",
    level: "Intermediate",
    category: "Cloud Computing",
    rating: 4.8,
    studentsEnrolled: 1289,
    image:
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=250&fit=crop",
    features: [
      "AWS Certification Prep",
      "Hands-on Labs",
      "Real-world Projects",
      "Industry Best Practices",
      "Career Support",
    ],
    curriculum: [
      "Cloud Computing Basics",
      "AWS Core Services",
      "EC2 & VPC",
      "Storage Solutions",
      "Database Services",
      "Security & IAM",
      "Monitoring & Logging",
      "Certification Preparation",
    ],
    prerequisites: ["Basic networking knowledge", "Linux fundamentals"],
    certificateProvided: true,
    language: "English",
    lastUpdated: "2024-12-02",
    tags: [
      "AWS",
      "Cloud Computing",
      "DevOps",
      "Infrastructure",
      "Certification",
    ],
  },
  {
    id: "6",
    title: "Cybersecurity Fundamentals",
    description:
      "Learn essential cybersecurity concepts, tools, and techniques to protect digital assets and networks.",
    instructor: "Colonel Rahul Mehta",
    instructorImage:
      "https://images.unsplash.com/photo-1556157382-97eda2d62296?w=100&h=100&fit=crop&crop=face",
    price: 11999,
    originalPrice: 17999,
    duration: "12 weeks",
    level: "Beginner",
    category: "Cybersecurity",
    rating: 4.7,
    studentsEnrolled: 1456,
    image:
      "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop",
    features: [
      "Ethical Hacking",
      "Security Tools",
      "Risk Assessment",
      "Incident Response",
      "Industry Certification Prep",
    ],
    curriculum: [
      "Cybersecurity Basics",
      "Network Security",
      "Ethical Hacking",
      "Vulnerability Assessment",
      "Incident Response",
      "Cryptography",
      "Compliance & Governance",
      "Career Guidance",
    ],
    prerequisites: ["Basic computer knowledge", "Networking fundamentals"],
    certificateProvided: true,
    language: "English",
    lastUpdated: "2024-11-29",
    tags: [
      "Cybersecurity",
      "Ethical Hacking",
      "Network Security",
      "Privacy",
      "Compliance",
    ],
  },
];

export const categories = [
  "All Categories",
  "Web Development",
  "Data Science",
  "Mobile Development",
  "Design",
  "Cloud Computing",
  "Cybersecurity",
  "DevOps",
  "Artificial Intelligence",
];

export const levels = ["All Levels", "Beginner", "Intermediate", "Advanced"];
export const durations = [
  "All Durations",
  "1-8 weeks",
  "9-16 weeks",
  "17+ weeks",
];
export const priceRanges = [
  "All Prices",
  "Free",
  "₹1-₹10,000",
  "₹10,001-₹20,000",
  "₹20,000+",
];
