import { JobNotification, HiringService } from "../types/hiring";

export const jobNotifications: JobNotification[] = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    company: "Microsoft",
    location: "Hyderabad, India",
    type: "full-time",
    experience: "3-5 years",
    salary: "₹25-35 LPA",
    description:
      "We're looking for a skilled Frontend Developer to join our Azure team and work on cutting-edge cloud solutions.",
    requirements: ["React.js", "TypeScript", "Azure", "GraphQL", "Jest"],
    postedDate: new Date("2024-01-15"),
    deadline: new Date("2024-02-15"),
    isExternal: false,
  },
  {
    id: "2",
    title: "Full Stack Engineer",
    company: "Amazon",
    location: "Bangalore, India",
    type: "full-time",
    experience: "2-4 years",
    salary: "₹20-30 LPA",
    description:
      "Join our Prime Video team to build scalable web applications serving millions of users worldwide.",
    requirements: ["Node.js", "React", "AWS", "MongoDB", "Docker"],
    postedDate: new Date("2024-01-18"),
    deadline: new Date("2024-02-20"),
    isExternal: false,
  },
  {
    id: "3",
    title: "SDE Intern",
    company: "Google",
    location: "Remote",
    type: "internship",
    experience: "0-1 years",
    salary: "₹80k/month",
    description:
      "12-week internship program working on Google Search infrastructure and machine learning projects.",
    requirements: ["Python", "Java", "Data Structures", "Algorithms", "ML"],
    postedDate: new Date("2024-01-20"),
    deadline: new Date("2024-03-01"),
    isExternal: false,
  },
  {
    id: "4",
    title: "DevOps Engineer",
    company: "Uber",
    location: "Hyderabad, India",
    type: "full-time",
    experience: "3-6 years",
    salary: "₹22-32 LPA",
    description:
      "Scale Uber's platform infrastructure to support millions of rides and deliveries globally.",
    requirements: ["Kubernetes", "AWS", "Terraform", "Python", "Monitoring"],
    postedDate: new Date("2024-01-22"),
    deadline: new Date("2024-02-25"),
    isExternal: false,
  },
  {
    id: "5",
    title: "Product Manager",
    company: "Flipkart",
    location: "Bangalore, India",
    type: "full-time",
    experience: "4-7 years",
    salary: "₹30-45 LPA",
    description:
      "Lead product strategy for Flipkart's e-commerce platform, driving innovation in shopping experience.",
    requirements: [
      "Product Strategy",
      "Analytics",
      "A/B Testing",
      "SQL",
      "User Research",
    ],
    postedDate: new Date("2024-01-25"),
    deadline: new Date("2024-03-05"),
    isExternal: false,
  },
];

export const hiringServices: HiringService[] = [
  {
    id: "1",
    name: "Premium Career Coaching",
    description: "1-on-1 personalized career guidance with industry experts",
    features: [
      "Resume Review & Optimization",
      "Mock Interview Sessions",
      "LinkedIn Profile Enhancement",
      "Salary Negotiation Guidance",
      "Career Path Planning",
    ],
    pricing: "₹15,000/month",
    rating: 4.9,
    reviews: 234,
  },
  {
    id: "2",
    name: "Job Placement Guarantee",
    description: "Complete job placement support with money-back guarantee",
    features: [
      "Guaranteed Job Placement",
      "Company-specific Preparation",
      "Interview Scheduling",
      "Offer Negotiation Support",
      "6-month Post-placement Support",
    ],
    pricing: "₹5,000 (Refundable)",
    rating: 4.8,
    reviews: 156,
  },
  {
    id: "3",
    name: "Executive Search",
    description: "Premium headhunting service for senior positions",
    features: [
      "Exclusive Job Opportunities",
      "C-level Position Access",
      "Confidential Job Search",
      "Executive Branding",
      "Industry Network Access",
    ],
    pricing: "₹10,000+",
    rating: 4.7,
    reviews: 89,
  },
  {
    id: "4",
    name: "Quick Hire Support",
    description: "Fast-track job application and interview process",
    features: [
      "Priority Application Processing",
      "Fast-track Interviews",
      "Same-day Feedback",
      "Quick Onboarding",
      "Emergency Placement",
    ],
    pricing: "₹8,000/applic.",
    rating: 4.6,
    reviews: 412,
  },
];
